CREATE TABLE THEME(
	THEME_NO NUMBER,
	THEME_NAME VARCHAR2(30),
	CONSTRAINT THEME_PK PRIMARY KEY(THEME_NO)
);

CREATE TABLE BOARD(
RCD_NO NUMBER, -- 레코드 번호
GRP_NO NUMBER, -- 그룹번호
THEME_NO NUMBER, -- 테마번호
USR_NAME VARCHAR2(30), -- 작성자
USR_MAIL VARCHAR2(30), -- 작성자 이메일
USR_SUBJECT VARCHAR2(250), -- 
USR_CONTENT VARCHAR2(1000),
USRPASS VARCHAR2(30),
USR_FILE_NAME VARCHAR2(255),
USR_FILE_SIZE NUMBER,
USR_DATE VARCHAR2(30),
USR_REFER NUMBER, -- 참조
RCD_LEVEL NUMBER, -- 레벨
RCD_ORDER NUMBER, -- 순서
CONSTRAINT BOARD_PK PRIMARY KEY(RCD_NO),
CONSTRAINT BOARD_FK_THEME FOREIGN KEY(THEME_NO) REFERENCES THEME(THEME_NO)
);

INSERT INTO THEME(THEME_NO,THEME_NAME)
VALUES (SEQ.NEXTVAL, '회원관리'); -- 시퀀스 141
INSERT INTO THEME(THEME_NO,THEME_NAME)

INSERT INTO THEME(THEME_NO,THEME_NAME)
VALUES (SEQ.NEXTVAL, '자유 게시판'); -- 시퀀스 142
SELECT * FROM THEME;

-- GRP_NO 는 원글에 딸린 댓글을 구별하기 위한 값으로
-- 원글만 존재할 경우는 GRP_NO 는 널로주고
-- 만약, 댓글이 달리면 그때 원글에 RCD_NO 와 동일한 값을 부여하는 것으로 한다.
-- 이때, 댓글도 원글과 GRP_NO는 동일하게 묶는다.
-- RCD_LEVEL 은 이 글이 원글인지, 댓글인지, 대댓글인지를 판별할 수 있는 값으로 댑스에 따라 수가 증가한다.
-- 원글이면 0, 1단계 댓글이면 1, 대댓글(2단계)이면 2 이와같은 식으로 추가가 된다.
-- 다음의 내용은 JSP 물고기 책의 p.510에서 찾아볼 수 있다(참고).
-- RCD_ORDER 는 댓글이든, 원글이든, 대댓글이든 시간 순서대로 보여주는 값.
INSERT INTO BOARD(RCD_NO,THEME_NO,RCD_LEVEL,RCD_ORDER,USR_SUBJECT,USR_CONTENT)
VALUES(SEQ.NEXTVAL,142,0,1,'테스트','자유게시판 첫번째 테스트 글입니다.'); --시퀀스 161, 162번 내용
